version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  airflow-webserver:
    build: .
    container_name: airflow-webserver
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__SECRET_KEY: 'my_secret_key'
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./csv_data:/opt/airflow/csv_data  # Монтирование папки с CSV-файлами
      - ./logs:/opt/airflow/logs
    entrypoint: >
      sh -c "airflow db init && airflow webserver"

  airflow-scheduler:
    build: .
    container_name: airflow-scheduler
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__SECRET_KEY: 'my_secret_key'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./csv_data:/opt/airflow/csv_data  # Монтирование папки с CSV-файлами
      - ./logs:/opt/airflow/logs
    entrypoint: >
      sh -c "airflow db check && airflow scheduler"
